- arm-ttk/Expand-AzTemplate.ps1
Changing load behavior to only read .JSON files (issue 5400) and fixing ScriptAnalyzer issues.
> File load fix (5400)

- arm-ttk/README.md
- arm-ttk/Test-AzTemplate.sh
Fixes #54 
modified:   arm-ttk/README.md
modified:   arm-ttk/Test-AzTemplate.sh
> On branch edburns-54-test-aztemplate-mac Account for use of greadlink on macOS

- arm-ttk/testcases/deploymentTemplate/IDs-Should-Be-Derived-From-ResourceIDs.test.ps1
- unit-tests/IDs-Should-Be-Derived-From-ResourceIDs/Pass/exceptions-that-should-pass.json
> added exceptions to IDs tests

- arm-ttk/testcases/deploymentTemplate/Parameters-Must-Be-Referenced.test.ps1
- unit-tests/Parameters-Must-Be-Referenced/Fail/NotUsed.json
- unit-tests/Parameters-Must-Be-Referenced/Pass/Different-Case-In-Reference.json
- unit-tests/Parameters-Must-Be-Referenced/Pass/MarketplaceSample.path.txt
- unit-tests/Parameters-Must-Be-Referenced/Pass/SkipMe.json
- unit-tests/Parameters-Must-Be-Referenced/Pass/Used-Directly-In-Variables.json
- unit-tests/Parameters-Must-Be-Referenced/Pass/Used-In-Concat.json
Fixing https://github.com/Azure/arm-ttk/issues/51 
Adding documentation / unit tests
> Parameters must be referenced (https://github.com/Azure/arm-ttk/issues/51)

- arm-ttk/testcases/CreateUIDefinition/Controls-In-Outputs-Must-Exist.test.ps1
- unit-tests/Controls-In-Outputs-Must-Exist/Fail/Missing-ControlName/CreateUIDefinition.json
- unit-tests/Controls-In-Outputs-Must-Exist/Fail/Missing-ControlName/azureDeploy.json
- unit-tests/Controls-In-Outputs-Must-Exist/Fail/Missing-ElementName/CreateUIDefinition.json
- unit-tests/Controls-In-Outputs-Must-Exist/Fail/Missing-ElementName/azureDeploy.json
- unit-tests/Controls-In-Outputs-Must-Exist/Fail/Missing-Step/CreateUIDefinition.json
- unit-tests/Controls-In-Outputs-Must-Exist/Fail/Missing-Step/azureDeploy.json
- unit-tests/Controls-In-Outputs-Must-Exist/Pass/MarketplaceSample.path.txt
> Controls in outputs must exist (4495)

- arm-ttk/arm-ttk.ezformat.ps1
- arm-ttk/arm-ttk.format.ps1xml
Making color-scheme aware, adding index of match when failure is a [Text.RegularExpressions.Match]
> Improved output formatting (4168)

- arm-ttk/arm-ttk.ezformat.ps1
- arm-ttk/arm-ttk.format.ps1xml
> Formatter fixes (Git Hub Issue 106)

- arm-ttk/testcases/deploymentTemplate/Location-Should-Not-Be-Hardcoded.test.ps1
- arm-ttk/testcases/deploymentTemplate/artifacts-parameter.test.ps1
> Fixed "delcaration" typos to "declaration" 

- arm-ttk/Expand-AzTemplate.ps1
- arm-ttk/Test-AzTemplate.ps1
Allowing tests to be run only on a CreateUIDefinition (4567).
Updating help for -TestParameter (4687)
> Test-AzTemplate improvements (4687, 4597)

- arm-ttk/arm-ttk.ezformat.ps1
- arm-ttk/arm-ttk.format.ps1xml
Attempting to fix #125 (updating logging commands, removing extra newline from output)
> Attempting fix on AzureDevOps formatter output.

- arm-ttk/testcases/deploymentTemplate/Location-Should-Not-Be-Hardcoded.test.ps1
was causing the test to be skipped
> remove mandatory flag on switch parameter

- .github/workflows/run-unit-tests.yml
Improving Tracing, Publishing Test Results Artifact
> Updating run-unit-tests.yml

- arm-ttk/testcases/deploymentTemplate/ResourceIds-should-not-contain.test.ps1
- unit-tests/ResourceIds-should-not-contain/Pass/ResourceIds-should-not-contain.json
grouped concat|format for proper or behavior
> regex = fun

- arm-ttk/testcases/deploymentTemplate/Deployment-Resources-Must-Not-Be-Debug.test.ps1
- unit-tests/Deployment-Resources-Must-Not-Be-Debug/Fail/DebugSettingLogDetailUsed.json
- unit-tests/Deployment-Resources-Must-Not-Be-Debug/Pass/DebugSettingsLogDetailNone.json
> Debug setting log detail 105

- unit-tests/apiversions-should-be-recent/Pass/NonPreviewVersionWhereSamePreviewDateExists.json
> apiVersions-should-be-recent: Adding test for preview version ambiguity.

- arm-ttk/Format-AzTemplate.ps1
> Format-AzTemplate: Keeping array singletons as arrays.

- README.md
Added a few paragraphs to explain how to run the pester tests locally before submitting a commit or a PR
> Complement issue #194: running unit tests locally

- arm-ttk/testcases/CreateUIDefinition/VMSizes-Must-Match-Template.test.ps1
- unit-tests/VMSizes-Must-Match-Template/Pass/Element-Nested-In-Section/azureDeploy.json
Addressing #107  . Re-enabling test.
> Re-enabling VMSize match test #107

- arm-ttk/testcases/deploymentTemplate/DeploymentTemplate-Schema-Is-Correct.test.ps1
unit tests have a "pass" case for this, not sure what our pipeline will do with it ;)
> add warning for deprecated schema

- arm-ttk/Regex/ARM/Template_Expression.regex.txt
- arm-ttk/testcases/deploymentTemplate/adminUsername-Should-Not-Be-A-Literal.test.ps1
- arm-ttk/ttk.irregular.ps1
- unit-tests/adminUsername-Should-Not-Be-A-Literal/Fail/Literal-Variable-Property-Username.json
- unit-tests/adminUsername-Should-Not-Be-A-Literal/Fail/Literal-Variable-Username.json
> Fixing #37 admin user name variable literal

- arm-ttk/testcases/deploymentTemplate/CommandToExecute-Must-Use-ProtectedSettings-For-Secrets.test.ps1
- arm-ttk/ttk.irregular.ps1
- unit-tests/CommandToExecute-Must-Use-ProtectedSettings-For-Secrets/CommandToExecute-Must-Use-ProtectedSettings-For-Secrets.tests.ps1
- unit-tests/CommandToExecute-Must-Use-ProtectedSettings-For-Secrets/Fail/ListKeys.json
- unit-tests/CommandToExecute-Must-Use-ProtectedSettings-For-Secrets/Fail/UnsecuredParameter.json
- unit-tests/CommandToExecute-Must-Use-ProtectedSettings-For-Secrets/Pass/MarketplaceSample.path.txt
- unit-tests/CommandToExecute-Must-Use-ProtectedSettings-For-Secrets/Pass/list-function.json
> Fixing #148: CommandToExecute Must Use ProtectedSettings for Secrets

- arm-ttk/testcases/CreateUIDefinition/PasswordBoxes-Must-Have-Min-Length.test.ps1
- unit-tests/PasswordBoxes-Must-Have-Min-Length/Pass/Has-Expression-Constraint.json
> Fixing #39 - Allowing Expressions within Regex Constraint

- arm-ttk/testcases/deploymentTemplate/adminUsername-Should-Not-Be-A-Literal.test.ps1
As it was causing null references
> Fixing #297:  Removing vestigial code to check object parentage

- arm-ttk/testcases/CreateUIDefinition/HideExisting-Must-Be-Correctly-Handled.test.ps1
- unit-tests/HideExisting-Must-Be-Correctly-Handled/Fail/Missing-NewOrExisting.json
- unit-tests/HideExisting-Must-Be-Correctly-Handled/Fail/Missing-NewOrExisting.should.be.txt
- unit-tests/HideExisting-Must-Be-Correctly-Handled/Fail/Missing-Output.json
- unit-tests/HideExisting-Must-Be-Correctly-Handled/Fail/Missing-ResourceGroup.json
- unit-tests/HideExisting-Must-Be-Correctly-Handled/Fail/Missing-ResourceGroup.should.be.txt
- unit-tests/HideExisting-Must-Be-Correctly-Handled/HideExisting-Must-Be-Correctly-Handled.tests.ps1
- unit-tests/HideExisting-Must-Be-Correctly-Handled/Pass/MarketplaceSample.path.txt
Fixing #150 
Preplumbing for #142.
> Checking for required properties when resources could have HideExisting

- arm-ttk/testcases/deploymentTemplate/IDs-Should-Be-Derived-From-ResourceIDs.test.ps1
- unit-tests/IDs-Should-Be-Derived-From-ResourceIDs/Pass/exceptions-that-should-pass.json
Issue #274 
Tried to add it to `Linked issues` but I seem to be lacking the permissions.
> check for parent is 'tags', ignore

- arm-ttk/cache/AllAzureResources.init.cache.ps1
- arm-ttk/cache/AllEnvironments.init.cache.ps1
- arm-ttk/cache/AllImages.init.cache.ps1
Fixing #339
Sorting resources by name
Sorting environments by name 
Sorting images by URN
> 339 sorting cache

- arm-ttk/testcases/CreateUIDefinition/PasswordBoxes-Must-Have-Min-Length.test.ps1
- unit-tests/PasswordBoxes-Must-Have-Min-Length/Pass/Has-Regex-Constraint-With-Multiple-FixedLengths.json
> 187 RegEx Length Constraint Fix

- arm-ttk/testcases/deploymentTemplate/IDs-Should-Be-Derived-From-ResourceIDs.test.ps1
- unit-tests/IDs-Should-Be-Derived-From-ResourceIDs/Pass/dashboard-that-contains-id-should-pass.json
Added exclusion for Microsoft.Portal/dashboards ID check
Solution for issue #361
> Added exclusion for Microsoft.Portal/dashboards

- arm-ttk/testcases/deploymentTemplate/Location-Should-Not-Be-Hardcoded.test.ps1
- unit-tests/Location-Should-Not-Be-Hardcoded/Fail/no-parameters.json
- unit-tests/Location-Should-Not-Be-Hardcoded/Pass/no-parameters/azuredeploy.json
test was not correctly catching the case of using resourceGroup().location and no params were present
> fix 365 and add unit tests

- arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent-In-Reference-Functions.test.ps1
- unit-tests/apiVersions-Should-Be-Recent-In-Reference-Functions/Fail/old-apiVersion-FullReference.json
- unit-tests/apiVersions-Should-Be-Recent-In-Reference-Functions/Fail/old-apiVersion-NestedResource.json
- unit-tests/apiVersions-Should-Be-Recent-In-Reference-Functions/Fail/old-apiVersion-ReferencedByVariable.json
- unit-tests/apiVersions-Should-Be-Recent-In-Reference-Functions/Fail/old-apiVersion-in-List.json
- unit-tests/apiVersions-Should-Be-Recent-In-Reference-Functions/Fail/old-apiVersion-in-ListAccountSas.json
- unit-tests/apiVersions-Should-Be-Recent-In-Reference-Functions/Fail/old-apiVersion.json
- unit-tests/apiVersions-Should-Be-Recent-In-Reference-Functions/Pass/NoApiVersion.json
- unit-tests/apiVersions-Should-Be-Recent-In-Reference-Functions/Pass/NonPreviewVersionWhereSamePreviewDateExists.json
- unit-tests/apiVersions-Should-Be-Recent-In-Reference-Functions/apiVersions-Should-Be-Recent-In-Reference-Functions.tests.ps1
Fixing #155  and adding associated unit tests.
> 155 api version reference check

- .github/workflows/update-cache.yml
> update-cache.yml: Moving git config

- arm-ttk/testcases/deploymentTemplate/IDs-Should-Be-Derived-From-ResourceIDs.test.ps1
> 376: Add nodeAgentSkuId to list of property exceptions

- arm-ttk/testcases/deploymentTemplate/adminUsername-Should-Not-Be-A-Literal.test.ps1
- unit-tests/adminUsername-Should-Not-Be-A-Literal/Pass/ExpressionValue.json
(provided it is embedded in another ARM function)
> Fixing #317:  Allowing for a variable in adminUsername

- arm-ttk/testcases/CreateUIDefinition/Controls-In-Outputs-Must-Exist.test.ps1
- unit-tests/Controls-In-Outputs-Must-Exist/Pass/OutputtingObject/azuredeploy.json
- unit-tests/Controls-In-Outputs-Must-Exist/Pass/OutputtingObject/createUIDefinition.json
> Fixing #323 - Complex control references

- .github/workflows/run-unit-tests.yml
- arm-ttk/.github/workflows/run-unit-tests.yml
- arm-ttk/GitHubWorkflow/Jobs/TestPowerShellOnLinux.psd1
- arm-ttk/GitHubWorkflow/Jobs/UpdateTTKCache.psd1
- arm-ttk/GitHubWorkflow/Steps/InstallPester.ps1
- arm-ttk/GitHubWorkflow/Steps/RunPester.ps1
- arm-ttk/GitHubWorkflow/Steps/UpdateTTKCache.psd1
- arm-ttk/ttk.test.workflow.psdevops.ps1
Adding workflow definitions and making workflow use relative pathing. Fixing #189
> #189 - Workflow refactoring

- arm-ttk/Test-AzTemplate.ps1
- unit-tests/DeploymentTemplate-Schema-Is-Correct/Fail/NoSchema-But-Resources.json
> 175 Template Missing Schema

- arm-ttk/Expand-AzTemplate.ps1
- unit-tests/_arm-ttk-module/JSONC.module.tests.ps1
- unit-tests/_arm-ttk-module/Sample.jsonc
Adding support for JSONC files (Fixing #200 )
> #200 - JSONC Support

- arm-ttk/testcases/deploymentTemplate/CommandToExecute-Must-Use-ProtectedSettings-For-Secrets.test.ps1
- unit-tests/CommandToExecute-Must-Use-ProtectedSettings-For-Secrets/Fail/ListKeys.json
- unit-tests/CommandToExecute-Must-Use-ProtectedSettings-For-Secrets/Fail/UnsecuredParameter.json
- unit-tests/CommandToExecute-Must-Use-ProtectedSettings-For-Secrets/Pass/list-function.json
Fixing #318 :  Scoping CommandToExecute tests to type "CustomScript"
> 318 command to execute custom script

- arm-ttk/testcases/deploymentTemplate/DependsOn-Best-Practices.test.ps1
- unit-tests/DependsOn-Best-Practices/Fail/DependsOn-Has-If.json
- unit-tests/DependsOn-Best-Practices/Fail/DependsOn-Starts-With-Concat.json
- unit-tests/DependsOn-Best-Practices/Pass/DependsOn-Has-ResourceId.json
- unit-tests/DependsOn-Best-Practices/Pass/dependson-nested-if.json
allow if() in dependsOn test if not at the beginning of an expression
>  fix for dependsOn if() check

- arm-ttk/Test-AzTemplate.ps1
- unit-tests/IDs-Should-Be-Derived-From-ResourceIDs/Pass/IDs-in-InnerTemplates.json
Updating Logic to Detect InnerTemplate ranges (was unable to find start when more than one failure presented from a test)
> Test-AzTemplate:  Fixing #439.  

- arm-ttk/testcases/deploymentTemplate/Resources-Should-Not-Be-Ambiguous.test.ps1
- unit-tests/Resources-Should-Not-Be-Ambiguous/Fail/InnerTemplateAmbiguitity.json
- unit-tests/Resources-Should-Not-Be-Ambiguous/Pass/proxy-resource.json
- proxy resources don't need an rg specified so added the ability to except them
- clean up error message to more easily find the error
- formatting
- reduce unit tests to what's needed for the test
- I think that's it
> add exception for proxy resources, fix error msg

- arm-ttk/Regex/CreateUIDefinition/Output.regex.ps1
- arm-ttk/testcases/CreateUIDefinition/Allowed-Values-Should-Actually-Be-Allowed.test.ps1
- unit-tests/Allowed-Values-Should-Actually-Be-Allowed/Fail/OutputMismatch/README.md
- unit-tests/Allowed-Values-Should-Actually-Be-Allowed/Fail/OutputMismatch/azuredeploy.json
- unit-tests/Allowed-Values-Should-Actually-Be-Allowed/Fail/OutputMismatch/createUiDefinition.json
- unit-tests/Allowed-Values-Should-Actually-Be-Allowed/Pass/ValueAllowed/README.md
- unit-tests/Allowed-Values-Should-Actually-Be-Allowed/Pass/ValueAllowed/azuredeploy.json
- unit-tests/Allowed-Values-Should-Actually-Be-Allowed/Pass/ValueAllowed/createUiDefinition.json
- unit-tests/Allowed-Values-Should-Actually-Be-Allowed/Pass/ValueAllowedInSteps/README.md
- unit-tests/Allowed-Values-Should-Actually-Be-Allowed/Pass/ValueAllowedInSteps/azuredeploy.json
- unit-tests/Allowed-Values-Should-Actually-Be-Allowed/Pass/ValueAllowedInSteps/createUiDefinition.json
- unit-tests/Allowed-Values-Should-Actually-Be-Allowed/Pass/ValueAllowedInStepsSection/README.md
- unit-tests/Allowed-Values-Should-Actually-Be-Allowed/Pass/ValueAllowedInStepsSection/azuredeploy.json
- unit-tests/Allowed-Values-Should-Actually-Be-Allowed/Pass/ValueAllowedInStepsSection/createUiDefinition.json
> 424 allowed values fix

- arm-ttk/testcases/deploymentTemplate/Location-Should-Not-Be-Hardcoded.test.ps1
Comment does not correctly state rule behavior
> Fix comment about Location-Should-Not-Be-Hardcoded

- arm-ttk/Test-AzTemplate.ps1
- arm-ttk/arm-ttk.format.ps1xml
- arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1
- arm-ttk/ttk.ezformat.ps1
- unit-tests/apiversions-should-be-recent/Fail/OldApiVersion-In-SymbolicResource.json
> formatting fixes (#431 #565)

- unit-tests/apiVersions-Should-Be-Recent-In-Reference-Functions/Pass/ApiInPolicyRuleTemplate.json
- unit-tests/apiversions-should-be-recent/Fail/OldApiVersion-In-SymbolicResource.json
#479 appears fixed due to innertemplate changes.
> 479 api versions reference functions and nesting

- arm-ttk/testcases/deploymentTemplate/URIs-Should-Be-Properly-Constructed.test.ps1
- unit-tests/URIs-Should-Be-Properly-Constructed/Fail/URI-Using-Concat.json
- unit-tests/URIs-Should-Be-Properly-Constructed/Fail/URI-Using-Format.json
- unit-tests/URIs-Should-Be-Properly-Constructed/Pass/Concat-in-URL.json
- unit-tests/URIs-Should-Be-Properly-Constructed/Pass/MarketplaceSample.path.txt
- unit-tests/URIs-Should-Be-Properly-Constructed/URI-Using-Concat.json
- unit-tests/URIs-Should-Be-Properly-Constructed/URIs-Should-Be-Properly-Constructed.tests.ps1
- unit-tests/apiversions-should-be-recent/Fail/OldApiVersion-In-SymbolicResource.json
and ensuring that functions are allowed within a uri
> Fixing #417:  Re-adding URI format test 

- arm-ttk/testcases/deploymentTemplate/IDs-Should-Be-Derived-From-ResourceIDs.test.ps1
> fix for 554

- arm-ttk/Test-AzMarketplacePackage.ps1
- arm-ttk/arm-ttk.psm1
This PR : 
- creates a wrapper script for marketplace that can be run by publishers to check their packages before deploying on marketplace and to enable automated package validations.
> Wrapper script for marketplace 

- arm-ttk/Test-AzMarketplacePackage.ps1
Updating the function name in the file since there was a type previously
> Fix function name in the Test-AzMarketplacePackage file

- arm-ttk/testcases/deploymentTemplate/IDs-Should-Be-Derived-From-ResourceIDs.test.ps1
Added field attribute exceptions for Azure Sentinel
> Added exception for Sentinel

- arm-ttk/testcases/deploymentTemplate/IDs-Should-Be-Derived-From-ResourceIDs.test.ps1
Added field attribute exceptions for Azure Sentinel
> Added exceptions for Senitnel Props

- arm-ttk/Regex/ARM/Variable.regex.ps1
- unit-tests/Variables-Must-Be-Referenced/Fail/dollar.json
- unit-tests/Variables-Must-Be-Referenced/Pass/bicep-generated-var.json
- unit-tests/Variables-Must-Be-Referenced/Pass/dollar.json
- unit-tests/Variables-Must-Be-Referenced/Pass/sharp.json
> Allowing -Variable to contain dollar sign and number sign ( Fixing #667 )

- arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1
- unit-tests/apiversions-should-be-recent/Pass/old-apiVersion-skipped.json
prototype of skipping the apiVersion test on a single resource
> prototype skip of apiVersion test

- arm-ttk/testcases/deploymentTemplate/VM-Size-Should-Be-A-Parameter.test.ps1
- unit-tests/VM-Size-Should-Be-A-Parameter/Fail/NestedVMSize.json
- unit-tests/VM-Size-Should-Be-A-Parameter/Pass/NestedVMSize.json
- unit-tests/VM-Size-Should-Be-A-Parameter/Pass/VMSize-In-Alternate-VMTypes.json
> 643 vm size nesting fix

- arm-ttk/testcases/CreateUIDefinition/Parameters-Without-Default-Must-Exist-In-CreateUIDefinition.test.ps1
- unit-tests/Parameters-Without-Default-Must-Exist-In-CreateUIDefinition/Pass/nestedParameter/CreateUIDefinition.json
- unit-tests/Parameters-Without-Default-Must-Exist-In-CreateUIDefinition/Pass/nestedParameter/azureDeploy.json
> 681-CreateUIDefinition-Nested-Defaults

- arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent-In-Reference-Functions.test.ps1
- arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1
- unit-tests/apiversions-should-be-recent/Pass/Nested-API-Version.json
- unit-tests/apiversions-should-be-recent/Pass/apiManagmentHasAnApiVersionUnderProperties.json
and walking up references (Fixes #701)
> Fixing apiVersions tests.  Standardizing case (Fixes #696) 

- arm-ttk/testcases/CreateUIDefinition/PasswordBoxes-Must-Have-Min-Length.test.ps1
- unit-tests/PasswordBoxes-Must-Have-Min-Length/Pass/Has-Regex-Constraint-With-FixLength.json
- Resolved #742 .
- Added test case.
> Fix bug with "PasswordBoxes-Must-Have-Min-Length" test

- arm-ttk/testcases/deploymentTemplate/IDs-Should-Be-Derived-From-ResourceIDs.test.ps1
- unit-tests/IDs-Should-Be-Derived-From-ResourceIDs/Pass/template-that-contains-aws_iam_functionapp_id-should-pass.json
- unit-tests/IDs-Should-Be-Derived-From-ResourceIDs/Pass/template-that-contains-contentProductId-should-pass.json
- unit-tests/IDs-Should-Be-Derived-From-ResourceIDs/Pass/template-that-contains-dataCollectionEndpointId-should-pass.json
- unit-tests/IDs-Should-Be-Derived-From-ResourceIDs/Pass/template-that-contains-dataCollectionRuleImmutableId-should-pass.json
Add skip validations for contentProductId and id for arm-ttk
After running test locally and shows last 4 lines as passed:
> Added skip ids to IDs-Should-Be-Derived-From-ResourceIDs.test

- arm-ttk/arm-ttk.psd1
Updating latest release version to 0.24
> Updating latest release version to 0.24
