arm-ttk/Find-JsonContent.ps1
It looks like the problem was there was no parent object (are using $templateObject.Resources | Find-JsonContent in the apiVersions test).
Fixed in three ways:
* We guard against a null property now
* We populate the $Property for a -Key -Value match when we match (the other fix only covered -Key)
* We switch to a common codepath for all three scenarios.
=> Find-JsonContent bugfix

arm-ttk/Expand-AzTemplate.ps1
The command used to try and check if $templatePath is a file gives a false positive if the folder name has a period in it. I have updated the command to check for an actual file rather than using the name.
=> Change command to check item is a file

arm-ttk/testcases/deploymentTemplate/Parameters-Must-Be-Referenced.test.ps1, arm-ttk/testcases/deploymentTemplate/Variables-Must-Be-Referenced.test.ps1
Fixing by simplifying: no longer attempting to match a reference before the parameter/variable start
=> Simplified Verification for Referenced Parameters / Variables. (Fix for 5308)

arm-ttk/testcases/deploymentTemplate/Template-Should-Not-Contain-Blanks.test.ps1
Policy rules need to check against empty strings in some cases.
=> Add exception for notEquals in policyRule

arm-ttk/Find-JsonContent.ps1
=> Find-JSONContent now returns each matching property as a unique string.

arm-ttk/testcases/CreateUIDefinition/Textboxes-Are-Well-Formed.test.ps1
Suppressing errant output and adding warning for lack of length constraint.
=> TextBox issues (GitHub Issue 94, Azure DevOps Backlog 4064)

arm-ttk/testcases/deploymentTemplate/Variables-Must-Be-Referenced.test.ps1, unit-tests/Variables-Must-Be-Referenced/Pass/Variable-List-Value.json
Fix for #116 
When the variable value was a list, it was incorrectly assuming it should be a copy variable.
=> Variable reference fix 116

arm-ttk/testcases/deploymentTemplate/IDs-Should-Be-Derived-From-ResourceIDs.test.ps1
Added the following to the allowedExpressions hash table 
```
"servicePrincipalClientId",
"clientId",
"appId",
"tenantId",
"objectId"
```
=> Updated allowedExpressions to include additional 'Id' parameters

arm-ttk/testcases/deploymentTemplate/Virtual-Machines-Should-Not-Be-Preview.test.ps1, unit-tests/Virtual-Machines-Should-Not-Be-Preview/Pass/hdi-cluster-storage-profile.json
Currently the check will trigger a false positive if a variable or parameter is named 'storageProfile'.  Add a check to filter the results from Find-JsonContent to only include nodes where the parent object is a VM or VMSS.  Testing done: Tested script locally with vm and vmss templates manually modified to include "-preview" in the version field.  This might introduce a limitation of not finding cases where a variable named 'storageProfile' is defined and actually contains an 'imageReference', which is later used as the value for the 'storageProfile' field of a VM or VMSS.  This should also address https://github.com/Azure/arm-ttk/issues/122 which I'm guessing is happening because the prereq template for the HDI cluster includes a storageProfile property …
=> Limit check to virtualMachines and virtualMachineScaleSets

arm-ttk/testcases/deploymentTemplate/Template-Should-Not-Contain-Blanks.test.ps1
regarding #167
This allowes the Access control property 'allowedCallerIpAddresses' to be empty.
- Added allowedCallerIpAddresses
- remove white spaces
=> Allowed 'allowedCallerIpAddresses' to be Blank

arm-ttk/testcases/CreateUIDefinition/CreateUIDefinition-Must-Not-Have-Blanks.test.ps1, unit-tests/CreateUIDefinition-Must-Not-Have-Blanks/Fail/CreateUIDefinition-With-EmptyObject/createUiDefinition.json
Flagging empty object/string within otherwise empty array.
Fixing test case so that the empty item is not in basics, where empty items are permitted.
=> CreateUiDefinition-Must-Not-Have-Blanks fix

arm-ttk/arm-ttk.format.ps1xml, arm-ttk/ttk.ezformat.ps1
(avoiding it being counted for coverage, which produces odd errors).
=> Renaming .ezformat file 

arm-ttk/testcases/deploymentTemplate/ResourceIds-should-not-contain.test.ps1, unit-tests/ResourceIds-should-not-contain/Fail/list-concat.json
using a var for part of the regex was not working, fixed so it passes unit tests
=> remove fancy regex that wasn't working

arm-ttk/testcases/CreateUIDefinition/Textboxes-Are-Well-Formed.test.ps1, arm-ttk/testcases/CreateUIDefinition/Validations-Must-Have-Message.test.ps1, unit-tests/Textboxes-Are-Well-Formed/Fail/Textboxes-With-Invalid-Regex-Validations/azuredeploy.json, unit-tests/Textboxes-Are-Well-Formed/Fail/Textboxes-With-Invalid-Regex-Validations/createUiDefinition.json, unit-tests/Textboxes-Are-Well-Formed/Fail/Textboxes-With-Invalid-Regex/azuredeploy.json, unit-tests/Textboxes-Are-Well-Formed/Fail/Textboxes-With-Invalid-Regex/createUiDefinition.json, unit-tests/Textboxes-Are-Well-Formed/Fail/Textboxes-Without-Constrains-ValidationMessage/azuredeploy.json, unit-tests/Textboxes-Are-Well-Formed/Fail/Textboxes-Without-Constrains-ValidationMessage/createUiDefinition.json, unit-tests/Textboxes-Are-Well-Formed/Fail/Textboxes-Without-Regex/azuredeploy.json, unit-tests/Textboxes-Are-Well-Formed/Fail/Textboxes-Without-Regex/createUiDefinition.json, unit-tests/Textboxes-Are-Well-Formed/Pass/Textboxes-With-Constrains-Regex/azuredeploy.json, unit-tests/Textboxes-Are-Well-Formed/Pass/Textboxes-With-Constrains-Regex/createUiDefinition.json, unit-tests/Textboxes-Are-Well-Formed/Pass/Textboxes-With-Constrains-Validations/azuredeploy.json, unit-tests/Textboxes-Are-Well-Formed/Pass/Textboxes-With-Constrains-Validations/createUiDefinition.json, unit-tests/Validations-Must-Have-Message/Fail/Validations-Without-Message/azuredeploy.json, unit-tests/Validations-Must-Have-Message/Fail/Validations-Without-Message/createUiDefinition.json, unit-tests/Validations-Must-Have-Message/Pass/Validation-With-Message/azuredeploy.json, unit-tests/Validations-Must-Have-Message/Pass/Validation-With-Message/createUiDefinition.json
For issue: https://github.com/Azure/arm-ttk/issues/208.
modified: arm-ttk/testcases/CreateUIDefinition/Textboxes-Are-Well-Formed.test.ps1
Support constraints.validations schema.
Testcase:
1. textbox without regex, throw error message: `Textbox $($textbox.Name) is missing constraints.regex or regex property in constraints.validations items`
2. textbox with constraints.regex, test length constraint
3. textbox with constraints.validations[i].regex, test length constraint
4. text validation message.
=> Support UIDefinition.TextBox.constraints.validations

arm-ttk/testcases/deploymentTemplate/IDs-Should-Be-Derived-From-ResourceIDs.test.ps1
Some exceptions were in the allowedExpressions array and should not be... fixed that.  Also removed serverFarm since it's a resourceId and variables/params are allowedExpressions now.
=> fix exceptions and allowedExpressions

arm-ttk/testcases/deploymentTemplate/IDs-Should-Be-Derived-From-ResourceIDs.test.ps1
The vlanId in Microsoft.Network/expressRouteCircuits is not an resourceId...
More info here: https://docs.microsoft.com/en-us/azure/expressroute/expressroute-howto-routing-portal-resource-manager
=> The vlanId in Microsoft.Network/expressRouteCircuits is not an resourceId

arm-ttk/testcases/deploymentTemplate/DeploymentTemplate-Must-Not-Contain-Hardcoded-Uri.test.ps1
=> Removing trafficmanager.net from DeploymentTemplate-Must-Not-Contain-Hardcoded-Uri

arm-ttk/testcases/deploymentTemplate/IDs-Should-Be-Derived-From-ResourceIDs.test.ps1, unit-tests/IDs-Should-Be-Derived-From-ResourceIDs/Pass/exceptions-that-should-pass.json
I found while running the tests on one of my arm templates that it would error due to policyDefinitionReferenceId not being right.
https://docs.microsoft.com/en-us/azure/templates/microsoft.authorization/policysetdefinitions specifies PolicyDefinitionReference.policyDefinitionReferenceId to be 'A unique id (within the policy set definition) for this policy definition reference.'
This pull request updates the exclusion list to include the policyDefinitionReferenceId so it is not incorrectly flagged up.
=> Update to exclude policyDefinitionReferenceId on Ids should be derived from resourceids

arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1, unit-tests/apiversions-should-be-recent/Fail/api-version-is-an-expression.json, unit-tests/apiversions-should-be-recent/Fail/not-a-string.json, unit-tests/apiversions-should-be-recent/Fail/old-apiVersion.json, unit-tests/apiversions-should-be-recent/Fail/preview-when-newer-is-available.json, unit-tests/apiversions-should-be-recent/Pass/apiManagmentHasAnApiVersionUnderProperties.json
When an apiVersion has a preview the matches the latest, we don't enforce the latest.  This should fix that...
Also added unit tests, we had very few so hard to track regressions.
=> fix apiVersion and preview version being the same

arm-ttk/testcases/CreateUIDefinition/Textboxes-Are-Well-Formed.test.ps1, unit-tests/Textboxes-Are-Well-Formed/Pass/Textboxes-With-Length-Constrains-Regex/azuredeploy.json, unit-tests/Textboxes-Are-Well-Formed/Pass/Textboxes-With-Length-Constrains-Regex/createUiDefinition.json, unit-tests/Textboxes-Are-Well-Formed/Pass/Textboxes-Without-Length-Constrains-Regex/azuredeploy.json, unit-tests/Textboxes-Are-Well-Formed/Pass/Textboxes-Without-Length-Constrains-Regex/createUiDefinition.json
modified:   arm-ttk/testcases/CreateUIDefinition/Textboxes-Are-Well-Formed.test.ps1
- When testing for presence of length constraint, test at beginning of regex as well.
=> When testing for presence of length constraint, test at beginning of regex as well.

arm-ttk/testcases/deploymentTemplate/Parameters-Must-Be-Referenced.test.ps1, arm-ttk/testcases/deploymentTemplate/Template-Should-Not-Contain-Blanks.test.ps1
Line numbers are reported in three deploymentTemplate checks: ResourceIds-should-not-contain, Template-Should-Not-Contain-Blanks, and Parameters-Must-Be-Referenced. The first outputs as `TargetObject` an object with the value in its `lineNumber` property. Adding the same property for the output objects of the two remaining checks. It's needed for TTK's first integration into [template-analyzer](https://github.com/Azure/template-analyzer).
=> Add line number info to error's target objects

arm-ttk/testcases/deploymentTemplate/IDs-Should-Be-Derived-From-ResourceIDs.test.ps1, unit-tests/IDs-Should-Be-Derived-From-ResourceIDs/Fail/documentdb-sqldatabases-that-contains-invalid-id-property-should-fail.json, unit-tests/IDs-Should-Be-Derived-From-ResourceIDs/Pass/documentdb-sqldatabases-that-contains-resource-id-should-pass.json
This PR adds an exception to the following type: Microsoft.DocumentDB/databaseAccounts/sqlDatabases but only to resource.id property.
Added a negative test to test that any other id outside of 'resource' property bag should get flagged.
=> Added documentdb / sqldatabases exception

arm-ttk/testcases/CreateUIDefinition/Outputs-Must-Be-Present-In-Template-Parameters.test.ps1
Deploying a managed application with an assigned managed identity from the market place requires adding a special parameters 'managedIdenity' in the output section of the createUiDefinition.json file. This is a special parameter that exists only in the generated template and should be skip accordingly in the tests.
=> support 'managedIdentity' special parameter

arm-ttk/Test-AzTemplate.ps1, arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1
Because $templateObject.resources was being piped into Find-JSONContent, the JSONPath was returned with an unexpected pattern that missed multiple apis.
=> Fixing #385 (apiversion fix)

arm-ttk/Expand-AzTemplate.ps1, arm-ttk/Resolve-JSONContent.ps1, arm-ttk/Test-AzTemplate.ps1, unit-tests/_arm-ttk-module/InnerTemplate.module.tests.ps1, unit-tests/_arm-ttk-module/InnerTemplateWithEscapeSequence.json, unit-tests/_arm-ttk-module/JSONC.module.tests.ps1, unit-tests/_arm-ttk-module/JSONContentCommands.tests.ps1, unit-tests/_arm-ttk-module/NestedInnerTemplates.json
To avoid comparison issues.
This was causing the TargetIndex to be incorectly compared, which in turn caused Resolve-JSONContent to fail to find the match, which in turn caused the template to fail to snip at the right locations (and thus become corrupted)
=> Resolve-JSONContent:  Fixes for Inner Template

arm-ttk/Expand-AzTemplate.ps1
May Fix SuperLinter integration problem in #487
=> Expand-AzTemplate:  Switching variable expansion to use Write-Debug 

arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1, unit-tests/apiversions-should-be-recent/Fail/apiVersion-duplicated-in-nested-resource.json
Ignoring parent resources whose namespace is duplicated in nested resources
=> Fixing #226 : Ignoring parent resources whose namespace is duplicated

arm-ttk/Test-AzTemplate.ps1, arm-ttk/testcases/CreateUIDefinition/Outputs-Must-Be-Present-In-Template-Parameters.test.ps1, unit-tests/Outputs-Must-Be-Present-In-Template-Parameters/Pass/InnerTemplate/azuredeploy.json, unit-tests/Outputs-Must-Be-Present-In-Template-Parameters/Pass/InnerTemplate/createUiDefinition.json
Error happens for `Outputs-Must-Be-Present-In-Template-Parameters` test case, when the main template has inner template, and the inner template does not have parameters the same from the UiDefinition outputs.  It's super common usage. Such case should pass.
Error message shows like:
```
[-] Outputs Must Be Present In Template Parameters (6209 ms)
output acrName does not exist in template.parameters
output aksAgentPoolNodeCount does not exist in template.parameters
output aksAgentPoolVMSize does not exist in template.parameters
output aksClusterName does not exist in template.parameters
output aksClusterRGName does not exist in template.parameters
```
=> On branch master: add inner template test case for Outputs-Must-Be-Present-In-Template-Parameters

arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1, unit-tests/apiversions-should-be-recent/Fail/OldApiVersion-In-Inner-Template.json, unit-tests/apiversions-should-be-recent/Pass/Api-In-Inner-Template.json
Calling an API in the inner template, test case `apiVersions-Should-Be-Recent` constructs the resource type by adding prefix "Microsoft.Resources/deployments", then getting resource type like "Microsoft.Resources/deployments/Microsoft.Network/dnsZones", which causes the test failed. This case should pass.
Error example:
```text
[-] apiVersions Should Be Recent (5359 ms)
The apiVersion 2020-07-01 was not found for the resource type: M
icrosoft.Resources/deployments/Microsoft.Network/networkSecurityGroups
The apiVersion 2020-07-01 was not found for the resource typ
e: Microsoft.Resources/deployments/Microsoft.Network/virtualNetworks
The apiVersion 2020-07-01 was not found for the resource typ
e: Microsoft.Resources/deployments/Microsoft.Network/publicIPAddresses
The apiVersion 2020-07-01 …
```
=> Add inner template test case for APIVersion-Should-Be-Recent

arm-ttk/Test-AzTemplate.cmd, arm-ttk/Test-AzTemplate.sh
I got all the test case passed, but the process exit with 1. And I found in Test-AzTemplate.sh `error.Count` is not equals to `Errors.Count`. We should use `Errors.Count` as it is defined in [Test-AzTemplate.ps1 line 392](https://github.com/Azure/arm-ttk/blob/d208d8bc8e5a12b04f69239881c0e4e460b9ed15/arm-ttk/Test-AzTemplate.ps1#L392)
I logged the difference:
```text
bamboo@cn-haiche-0107:/mnt/c/Users/haiche/Documents/wlsonaks/arm-ttk/arm-ttk$ sh Test-AzTemplate.sh -TemplatePath /mytemplates/arm
Validating arm\deletenodedeploy.parameters.json
deploymentParameters                                                                                                                                                                                                [+] DeploymentParameters Should Have …
```
=> On branch master: Fix error condition in Test.AzTemplate.sh and TestAzTemplate.cmd

arm-ttk/testcases/CreateUIDefinition/PasswordBoxes-Must-Have-Min-Length.test.ps1, unit-tests/PasswordBoxes-Must-Have-Min-Length/Pass/Has-Complex-Constraint.json, unit-tests/PasswordBoxes-Must-Have-Min-Length/Pass/Has-Complex-Constraint2.json
Adding additional tests to validate passwordbox length (re: #187)
Also, fixing a typo
=> Adding additional tests to validate passwordbox length

arm-ttk/testcases/deploymentTemplate/Location-Should-Not-Be-Hardcoded.test.ps1
Fixed typo in the location test file
mentioned here: https://github.com/Azure/arm-ttk/issues/610
=> Fixing typo paramSection > paramsSection (location issue)

arm-ttk/testcases/deploymentTemplate/VM-Size-Should-Be-A-Parameter.test.ps1, unit-tests/VM-Size-Should-Be-A-Parameter/Fail/nested-param.json, unit-tests/VM-Size-Should-Be-A-Parameter/Pass/azuredeploy.json
since we just check for any property named "vmSize" anywhere in the template, adding some info to the error message about which resource contains the error.
=> improved error message for vm size failure

arm-ttk/testcases/deploymentTemplate/IDs-Should-Be-Derived-From-ResourceIDs.test.ps1
According the Microsoft Support Engineer Tolani Odumosu, the "schemaId" property expects to receive the schema identifier value only, and not a resourceId. So, this exception rule allow to successfully pass IDs-Should-Be-Derived-From-ResourceIDs test
=> Add "schemaId" as exception property for IDs-Should-Be-Derived-From-ResourceIDs test

arm-ttk/testcases/deploymentTemplate/Parameter-Types-Should-Be-Consistent.test.ps1, unit-tests/Parameter-Types-Should-Be-Consistent/Fail/InconsistentParameterTypes.json, unit-tests/Parameter-Types-Should-Be-Consistent/Pass/ConsistentParameterTypes.json
Fix https://github.com/Azure/arm-ttk/issues/635
=> Fix#635 : Referenced Parameters incorrectly treated as type mismatch

arm-ttk/testcases/CreateUIDefinition/PasswordBoxes-Must-Have-Min-Length.test.ps1
Fix missing space when generating Warning if password minimum length is failing.
=> Fix missing space when generating Warning if password minimum length is failing.

unit-tests/Textboxes-Are-Well-Formed/Pass/Textboxes-With-Length-Constrains-Regex/createUiDefinition.json
Textboxes-With-Length-Constrains-Regex should not fail when length constraint is in the middle.
```json
{
"name": "issuerProvider",
"type": "Microsoft.Common.TextBox",
"label": "Custom Issuer Provider",
"toolTip": "certificate Issuer Provider",
"visible": "[equals(steps('Security').issuerProviderDropDown, 'Custom')]",
"defaultValue": "",
"constraints": {
"validations": [
{
"regex": "^[A-Za-z][A-Za-z0-9-]{1,61}[A-Za-z0-9]$",
"message": "The certificate issuer can only contain alphanumeric values, and hyphens, but may not end with a hyphen."
}
]
}          
}
```
=> Extend CreateUI Test Coverage

arm-ttk/testcases/CreateUIDefinition/Textboxes-Are-Well-Formed.test.ps1, unit-tests/Textboxes-Are-Well-Formed/Pass/Textboxes-With-Length-Constrains-Regex/createUiDefinition.json
fixes #731
- The test only checks to see if the length constraint has been provided at the start and end of the regex string but it is possible for the length constraint to be present anywhere in the string. 
- Additionally the current test only returns success if length constraint of the pattern `{m,n}` or `{m,}` is provided while there is a third valid option `{m}` which will return failure.
- Since we only need to check if length constraint has been provided somewhere in the input regex string there is no need to check the start and end of the string separately instead a search of the entire string should be sufficient.
- Added support for the `{m}` variant of length constraint which was not currently supported.
- Updated the Units Tests with additional test conditions to check a more …
=> Updated Regex used by Textbox Length Check Test

arm-ttk/testcases/CreateUIDefinition/Tooltips-Should-Be-Present.test.ps1, unit-tests/Tooltips-Should-Be-Present/Pass/EditableGridTooltipNotRequired/azuredeploy.json, unit-tests/Tooltips-Should-Be-Present/Pass/EditableGridTooltipNotRequired/createUiDefinition.json
Related to issue https://github.com/Azure/arm-ttk/issues/733
EditableGrid does not require tooltips in the public schema and this should be followed for toolkit also.
Additional test for the same has been added.
=> EditableGrid does not need tooltips

arm-ttk/ConvertFrom-JSON.ps1, arm-ttk/arm-ttk.psm1, unit-tests/apiversions-should-be-recent/Pass/Nested-API-Version.json
Fixing issue https://github.com/Azure/arm-ttk/issues/737
Running the template provided in the above issue, if using the custom ConvertFrom-JSON utility, it fails.
The code change here changes the utility used to be the default powershell version if the powershell major version is equal to or above 6.
There is a small fix in the convertfrom-json utility where for recognizing comments both the starting and ending characters are searched.
=> Changing convertfrom-json utility usage based on powershell version (powershell 6+ has utility for json comments)

arm-ttk/testcases/deploymentTemplate/Parameter-Types-Should-Be-Consistent.test.ps1, unit-tests/Parameter-Types-Should-Be-Consistent/Pass/bicepTemplate.json, unit-tests/Parameter-Types-Should-Be-Consistent/Pass/innerParamArrayBicepTemplate.json, unit-tests/Parameter-Types-Should-Be-Consistent/Pass/twoModuleBicepTemplate.json, unit-tests/apiversions-should-be-recent/Pass/Nested-API-Version.json
Before this fix if an inner template parameter referenced a parent template parameter, if the value of the inner template parameter was not in the form [parameters('parenttemplateparam').....] or  [parameters('parenttemplateparam')] then an error would be thrown. This PR fixes the regex where the error will not be thrown to include values like *parameter('parenttemplateparam')... or *parameter('parenttemplateparam'), or *parameter('parenttemplateparam')]
Also if the VALUE of an innertemplateparam is an object, then the correct value was not retrieved previously. This is also fixed.
Addressing issues:
https://github.com/Azure/arm-ttk/issues/745
(Removed the condition to have '[' before parameters and a comma can be accepted besides '.' and ']')
Test file …
=> Addressing fixes for GitHub issues 738, 753 and 745

arm-ttk/testcases/deploymentTemplate/Template-Should-Not-Contain-Blanks.test.ps1, unit-tests/Template-Should-Not-Contain-Blanks/Pass/requiredDataConnectors-empty-array-should-pass.json
Ignore "requiredDataConnectors" property if [].
After running tests locally we see below for the added test case on "requiredDataConnectors" property :
=> Added property requiredDataConnectors in Template-Should-Not-Contain-Blanks Test to skip if []

arm-ttk/testcases/deploymentTemplate/artifacts-parameter.test.ps1
Must be `_artifactsLocationSasToken` (instead of `_artifactsLocationsSasToke`)
=> Fixed typo in error message. Must be _artifactsLocationSasToken instead of _artifactsLocationsSasToke

arm-ttk/testcases/deploymentTemplate/artifacts-parameter.test.ps1
`defaultValue` instead of `defaulValue` (missing `t`)
=> Fixed typo in artifacts-parameter.test.ps1

arm-ttk/testcases/CreateUIDefinition/Tooltips-Should-Be-Present.test.ps1
Updated Tooltips-Should-Be-Present.test.ps1 to add Microsoft.Solutions.GraphApiControl to the list of controls that do not need to be checked for a ToolTip since Microsoft.Solutions.GraphApiControl has no UI.
=> Added Microsoft.Solutions.GraphApiControl to the no-ToolTip controls

arm-ttk/Format-Json.ps1, arm-ttk/README.md
This PR enables the functionality of outputting the test results generated by Test-AzTemplate and Test-AzMarketplacePackage in JSON format.
The MCISV team has requested this feature.
You can try it out with the following command(s):
`Test-AzTemplate -TemplatePath <path> | Format-JSON`
or
`Test-AzMarketplacePackage -TemplatePath <path> | Format-JSON`
=> Implemented functionality to convert the test result format into JSON

.github/workflows/run-unit-tests.yml, arm-ttk/arm-ttk.psd1, arm-ttk/testcases/deploymentTemplate/adminPassword-Should-Not-Be-A-Literal.test.ps1, arm-ttk/testcases/deploymentTemplate/adminUsername-Should-Not-Be-A-Literal.test.ps1, unit-tests/adminPassword-Should-Not-Be-A-Literal/Fail/Literal-Admin-AdminPassword.json, unit-tests/adminPassword-Should-Not-Be-A-Literal/Pass/ExpressionValue.json, unit-tests/adminPassword-Should-Not-Be-A-Literal/adminPassword-Should-Not-Be-A-Literal.tests.ps1, unit-tests/adminUsername-Should-Not-Be-A-Literal/Fail/Literal-Admin-AdminLogin.json
This PR checks if the admin passwords in templates are not literal strings and adds checks for additional admin usernames.
=> Adding new test for admin password and admin usernames
